import KnexSqlUtilities from "../utils/KnexSqlUtilities.js";
import { LoggingUtilities } from "../utils/logging/LoggingUtilities.js";
import { Exceptions } from "../exceptions/AppExceptions.js";
import { ITB_ANALYTIC_USER_ACTIVITY } from "../models/databases/tb_analytic_user_activity.js";
import { toMessage } from "../utils/errorUtils.js";

/**
 * Hearbeat service to handle tracking users that are currently on the webpage.
 */
export class HeartbeatService {
  constructor(private db: KnexSqlUtilities) {}

  /**
   * Insert heartbeat record into the database.
   * @param sessionId - Session ID of the user (Uniquely generated by the frontend).
   * @param username - Username of the user (If there is a token present).
   * @param ipAddress - IP address of the user.
   * @param userAgent - User agent of the user's browser.
   */
  async insertHeartbeatRecord({
    sessionId,
    username,
    ipAddress,
    userAgent,
  }: {
    sessionId: string;
    username: string;
    ipAddress: string;
    userAgent: string;
  }): Promise<void> {
    LoggingUtilities.service.debug(
      "HeartbeatService.insertHeartbeatRecord",
      `${username} - ${ipAddress} - ${userAgent}`,
    );

    try {
      await this.db.upsert<ITB_ANALYTIC_USER_ACTIVITY>(
        "tb_analytic_user_activity",
        {
          session_id: sessionId,
          user_id: username,
          last_seen_at: new Date().getTime(),
          ip_address: ipAddress,
          user_agent: userAgent,
        },
        "session_id",
        {
          last_seen_at: new Date().getTime(),
          ip_address: ipAddress,
          user_agent: userAgent,
          ...(username ? { user_id: username } : {}),
        },
      );
    } catch (error) {
      LoggingUtilities.service.error(
        "HeartbeatService.insertHeartbeatRecord",
        `Error inserting heartbeat record: ${toMessage(error)}`,
      );
      throw new Exceptions.EntityCreation("Heartbeat");
    }
  }
}
