import type { Knex } from "knex";

export async function up(knex: Knex): Promise<void> {
  await knex.schema.dropTableIfExists("tb_scenic_checklist");
  await knex.schema.dropTableIfExists("tb_scenic_spot");
}

export async function down(knex: Knex): Promise<void> {
  await knex.raw(`
    CREATE TABLE IF NOT EXISTS tb_scenic_checklist (
      id            BIGINT        NOT NULL AUTO_INCREMENT,
      username      VARCHAR(64)   NOT NULL,
      scenic_id     BIGINT        NOT NULL,
      visited       TINYINT(1)    NOT NULL DEFAULT 1,
      created_dt    BIGINT        NOT NULL,
      updated_dt    BIGINT        NULL,
      record_status VARCHAR(1)    NOT NULL DEFAULT 'A',
      PRIMARY KEY (id),
      UNIQUE KEY uq_user_scenic (username, scenic_id),
      INDEX idx_username (username)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
  `);

  // Seed data — only insert if the table is empty
  const [countResult] = await knex.raw("SELECT COUNT(*) AS cnt FROM tb_scenic_spot");
  if (Number(countResult[0].cnt) === 0) {
    const now = Date.now();
    await knex("tb_scenic_spot").insert([
      // ── 北京 Beijing ────────────────────────────────────────────────────────
      {
        name_zh: "故宫博物院",
        name_en: "Palace Museum (Forbidden City)",
        province: "北京",
        city: "北京市",
        province_en: "Beijing",
        city_en: "Beijing",
        sort_order: 1,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "颐和园",
        name_en: "Summer Palace",
        province: "北京",
        city: "北京市",
        province_en: "Beijing",
        city_en: "Beijing",
        sort_order: 2,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "天坛公园",
        name_en: "Temple of Heaven Park",
        province: "北京",
        city: "北京市",
        province_en: "Beijing",
        city_en: "Beijing",
        sort_order: 3,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "八达岭长城景区",
        name_en: "Badaling Great Wall",
        province: "北京",
        city: "北京市",
        province_en: "Beijing",
        city_en: "Beijing",
        sort_order: 4,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "明十三陵景区",
        name_en: "Ming Tombs",
        province: "北京",
        city: "北京市",
        province_en: "Beijing",
        city_en: "Beijing",
        sort_order: 5,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "奥林匹克公园",
        name_en: "Olympic Park",
        province: "北京",
        city: "北京市",
        province_en: "Beijing",
        city_en: "Beijing",
        sort_order: 6,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "圆明园景区",
        name_en: "Old Summer Palace (Yuanmingyuan)",
        province: "北京",
        city: "北京市",
        province_en: "Beijing",
        city_en: "Beijing",
        sort_order: 7,
        created_dt: now,
        record_status: "A",
      },
      // ── 天津 Tianjin ─────────────────────────────────────────────────────────
      {
        name_zh: "天津古文化街旅游区",
        name_en: "Tianjin Ancient Culture Street",
        province: "天津",
        city: "天津市",
        province_en: "Tianjin",
        city_en: "Tianjin",
        sort_order: 1,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "盘山风景名胜区",
        name_en: "Panshan Scenic Area",
        province: "天津",
        city: "蓟州区",
        province_en: "Tianjin",
        city_en: "Ji County",
        sort_order: 2,
        created_dt: now,
        record_status: "A",
      },
      // ── 河北 Hebei ────────────────────────────────────────────────────────────
      {
        name_zh: "山海关景区",
        name_en: "Shanhaiguan Pass",
        province: "河北",
        city: "秦皇岛市",
        province_en: "Hebei",
        city_en: "Qinhuangdao",
        sort_order: 1,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "承德避暑山庄及周围寺庙景区",
        name_en: "Chengde Mountain Resort and Surrounding Temples",
        province: "河北",
        city: "承德市",
        province_en: "Hebei",
        city_en: "Chengde",
        sort_order: 2,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "野三坡景区",
        name_en: "Yesanpo Scenic Area",
        province: "河北",
        city: "保定市",
        province_en: "Hebei",
        city_en: "Baoding",
        sort_order: 3,
        created_dt: now,
        record_status: "A",
      },
      // ── 山西 Shanxi ───────────────────────────────────────────────────────────
      {
        name_zh: "五台山景区",
        name_en: "Mount Wutai Scenic Area",
        province: "山西",
        city: "忻州市",
        province_en: "Shanxi",
        city_en: "Xinzhou",
        sort_order: 1,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "云冈石窟景区",
        name_en: "Yungang Grottoes",
        province: "山西",
        city: "大同市",
        province_en: "Shanxi",
        city_en: "Datong",
        sort_order: 2,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "平遥古城景区",
        name_en: "Pingyao Ancient City",
        province: "山西",
        city: "晋中市",
        province_en: "Shanxi",
        city_en: "Jinzhong",
        sort_order: 3,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "壶口瀑布风景名胜区",
        name_en: "Hukou Waterfall",
        province: "山西",
        city: "临汾市",
        province_en: "Shanxi",
        city_en: "Linfen",
        sort_order: 4,
        created_dt: now,
        record_status: "A",
      },
      // ── 内蒙古 Inner Mongolia ─────────────────────────────────────────────────
      {
        name_zh: "成吉思汗陵旅游区",
        name_en: "Genghis Khan Mausoleum",
        province: "内蒙古",
        city: "鄂尔多斯市",
        province_en: "Inner Mongolia",
        city_en: "Ordos",
        sort_order: 1,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "阿尔山—柴河旅游景区",
        name_en: "Arxan–Chaihe Scenic Area",
        province: "内蒙古",
        city: "兴安盟",
        province_en: "Inner Mongolia",
        city_en: "Xing'an League",
        sort_order: 2,
        created_dt: now,
        record_status: "A",
      },
      // ── 辽宁 Liaoning ─────────────────────────────────────────────────────────
      {
        name_zh: "沈阳故宫博物院",
        name_en: "Shenyang Imperial Palace",
        province: "辽宁",
        city: "沈阳市",
        province_en: "Liaoning",
        city_en: "Shenyang",
        sort_order: 1,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "大连老虎滩海洋公园·老虎滩极地馆",
        name_en: "Dalian Tiger Beach Ocean Park",
        province: "辽宁",
        city: "大连市",
        province_en: "Liaoning",
        city_en: "Dalian",
        sort_order: 2,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "本溪水洞景区",
        name_en: "Benxi Water Cave",
        province: "辽宁",
        city: "本溪市",
        province_en: "Liaoning",
        city_en: "Benxi",
        sort_order: 3,
        created_dt: now,
        record_status: "A",
      },
      // ── 吉林 Jilin ────────────────────────────────────────────────────────────
      {
        name_zh: "长白山景区",
        name_en: "Changbaishan Scenic Area",
        province: "吉林",
        city: "延边州",
        province_en: "Jilin",
        city_en: "Yanbian",
        sort_order: 1,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "伪满皇宫博物院",
        name_en: "Puppet Manchukuo Imperial Palace Museum",
        province: "吉林",
        city: "长春市",
        province_en: "Jilin",
        city_en: "Changchun",
        sort_order: 2,
        created_dt: now,
        record_status: "A",
      },
      // ── 黑龙江 Heilongjiang ───────────────────────────────────────────────────
      {
        name_zh: "镜泊湖景区",
        name_en: "Jingpohu (Mirror Lake) Scenic Area",
        province: "黑龙江",
        city: "牡丹江市",
        province_en: "Heilongjiang",
        city_en: "Mudanjiang",
        sort_order: 1,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "哈尔滨太阳岛风景区",
        name_en: "Harbin Sun Island Scenic Area",
        province: "黑龙江",
        city: "哈尔滨市",
        province_en: "Heilongjiang",
        city_en: "Harbin",
        sort_order: 2,
        created_dt: now,
        record_status: "A",
      },
      // ── 上海 Shanghai ─────────────────────────────────────────────────────────
      {
        name_zh: "上海野生动物园",
        name_en: "Shanghai Wild Animal Park",
        province: "上海",
        city: "上海市",
        province_en: "Shanghai",
        city_en: "Shanghai",
        sort_order: 1,
        created_dt: now,
        record_status: "A",
      },
      // ── 江苏 Jiangsu ──────────────────────────────────────────────────────────
      {
        name_zh: "苏州园林（拙政园）",
        name_en: "Suzhou Classical Gardens (Humble Administrator's Garden)",
        province: "江苏",
        city: "苏州市",
        province_en: "Jiangsu",
        city_en: "Suzhou",
        sort_order: 1,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "钟山风景名胜区",
        name_en: "Zhongshan Scenic Area (Sun Yat-sen Mausoleum)",
        province: "江苏",
        city: "南京市",
        province_en: "Jiangsu",
        city_en: "Nanjing",
        sort_order: 2,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "南京夫子庙—秦淮风光带景区",
        name_en: "Nanjing Confucius Temple–Qinhuai Scenic Belt",
        province: "江苏",
        city: "南京市",
        province_en: "Jiangsu",
        city_en: "Nanjing",
        sort_order: 3,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "扬州瘦西湖景区",
        name_en: "Yangzhou Slender West Lake",
        province: "江苏",
        city: "扬州市",
        province_en: "Jiangsu",
        city_en: "Yangzhou",
        sort_order: 4,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "周庄古镇景区",
        name_en: "Zhouzhuang Ancient Town",
        province: "江苏",
        city: "苏州市",
        province_en: "Jiangsu",
        city_en: "Suzhou",
        sort_order: 5,
        created_dt: now,
        record_status: "A",
      },
      // ── 浙江 Zhejiang ─────────────────────────────────────────────────────────
      {
        name_zh: "西湖风景名胜区",
        name_en: "West Lake Scenic Area",
        province: "浙江",
        city: "杭州市",
        province_en: "Zhejiang",
        city_en: "Hangzhou",
        sort_order: 1,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "雁荡山风景名胜区",
        name_en: "Yandangshan Scenic Area",
        province: "浙江",
        city: "温州市",
        province_en: "Zhejiang",
        city_en: "Wenzhou",
        sort_order: 2,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "普陀山风景名胜区",
        name_en: "Putuoshan Scenic Area",
        province: "浙江",
        city: "舟山市",
        province_en: "Zhejiang",
        city_en: "Zhoushan",
        sort_order: 3,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "乌镇景区",
        name_en: "Wuzhen Ancient Town",
        province: "浙江",
        city: "嘉兴市",
        province_en: "Zhejiang",
        city_en: "Jiaxing",
        sort_order: 4,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "千岛湖景区",
        name_en: "Qiandao Lake (Thousand Island Lake)",
        province: "浙江",
        city: "杭州市",
        province_en: "Zhejiang",
        city_en: "Hangzhou",
        sort_order: 5,
        created_dt: now,
        record_status: "A",
      },
      // ── 安徽 Anhui ────────────────────────────────────────────────────────────
      {
        name_zh: "黄山风景区",
        name_en: "Huangshan (Yellow Mountain) Scenic Area",
        province: "安徽",
        city: "黄山市",
        province_en: "Anhui",
        city_en: "Huangshan",
        sort_order: 1,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "西递宏村景区",
        name_en: "Xidi and Hongcun Ancient Villages",
        province: "安徽",
        city: "黄山市",
        province_en: "Anhui",
        city_en: "Huangshan",
        sort_order: 2,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "九华山风景区",
        name_en: "Jiuhuashan Scenic Area",
        province: "安徽",
        city: "池州市",
        province_en: "Anhui",
        city_en: "Chizhou",
        sort_order: 3,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "天柱山风景区",
        name_en: "Tianzhushan Scenic Area",
        province: "安徽",
        city: "安庆市",
        province_en: "Anhui",
        city_en: "Anqing",
        sort_order: 4,
        created_dt: now,
        record_status: "A",
      },
      // ── 福建 Fujian ───────────────────────────────────────────────────────────
      {
        name_zh: "武夷山景区",
        name_en: "Wuyishan Scenic Area",
        province: "福建",
        city: "南平市",
        province_en: "Fujian",
        city_en: "Nanping",
        sort_order: 1,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "永定—南靖土楼景区",
        name_en: "Yongding-Nanjing Fujian Tulou",
        province: "福建",
        city: "龙岩市",
        province_en: "Fujian",
        city_en: "Longyan",
        sort_order: 2,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "鼓浪屿景区",
        name_en: "Gulangyu Island",
        province: "福建",
        city: "厦门市",
        province_en: "Fujian",
        city_en: "Xiamen",
        sort_order: 3,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "泰宁风景名胜区",
        name_en: "Taining Scenic Area",
        province: "福建",
        city: "三明市",
        province_en: "Fujian",
        city_en: "Sanming",
        sort_order: 4,
        created_dt: now,
        record_status: "A",
      },
      // ── 江西 Jiangxi ──────────────────────────────────────────────────────────
      {
        name_zh: "庐山风景名胜区",
        name_en: "Lushan Scenic Area",
        province: "江西",
        city: "九江市",
        province_en: "Jiangxi",
        city_en: "Jiujiang",
        sort_order: 1,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "三清山旅游景区",
        name_en: "Sanqingshan Scenic Area",
        province: "江西",
        city: "上饶市",
        province_en: "Jiangxi",
        city_en: "Shangrao",
        sort_order: 2,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "龙虎山景区",
        name_en: "Longhushan Scenic Area",
        province: "江西",
        city: "鹰潭市",
        province_en: "Jiangxi",
        city_en: "Yingtan",
        sort_order: 3,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "井冈山旅游景区",
        name_en: "Jinggang Mountains Scenic Area",
        province: "江西",
        city: "吉安市",
        province_en: "Jiangxi",
        city_en: "Ji'an",
        sort_order: 4,
        created_dt: now,
        record_status: "A",
      },
      // ── 山东 Shandong ─────────────────────────────────────────────────────────
      {
        name_zh: "泰山景区",
        name_en: "Mount Tai Scenic Area",
        province: "山东",
        city: "泰安市",
        province_en: "Shandong",
        city_en: "Tai'an",
        sort_order: 1,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "曲阜三孔旅游区",
        name_en: "Qufu Three Confucian Sites",
        province: "山东",
        city: "曲阜市",
        province_en: "Shandong",
        city_en: "Qufu",
        sort_order: 2,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "蓬莱阁旅游区",
        name_en: "Penglai Pavilion Tourist Area",
        province: "山东",
        city: "烟台市",
        province_en: "Shandong",
        city_en: "Yantai",
        sort_order: 3,
        created_dt: now,
        record_status: "A",
      },
      // ── 河南 Henan ────────────────────────────────────────────────────────────
      {
        name_zh: "龙门石窟景区",
        name_en: "Longmen Grottoes",
        province: "河南",
        city: "洛阳市",
        province_en: "Henan",
        city_en: "Luoyang",
        sort_order: 1,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "嵩山少林景区",
        name_en: "Shaolin Temple at Songshan",
        province: "河南",
        city: "郑州市",
        province_en: "Henan",
        city_en: "Zhengzhou",
        sort_order: 2,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "云台山风景名胜区",
        name_en: "Yuntai Mountain Scenic Area",
        province: "河南",
        city: "焦作市",
        province_en: "Henan",
        city_en: "Jiaozuo",
        sort_order: 3,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "清明上河园",
        name_en: "Qingming Riverside Landscape Garden",
        province: "河南",
        city: "开封市",
        province_en: "Henan",
        city_en: "Kaifeng",
        sort_order: 4,
        created_dt: now,
        record_status: "A",
      },
      // ── 湖北 Hubei ────────────────────────────────────────────────────────────
      {
        name_zh: "武汉黄鹤楼公园",
        name_en: "Yellow Crane Tower Park",
        province: "湖北",
        city: "武汉市",
        province_en: "Hubei",
        city_en: "Wuhan",
        sort_order: 1,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "神农架景区",
        name_en: "Shennongjia Scenic Area",
        province: "湖北",
        city: "神农架林区",
        province_en: "Hubei",
        city_en: "Shennongjia",
        sort_order: 2,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "武当山风景名胜区",
        name_en: "Wudang Mountain Scenic Area",
        province: "湖北",
        city: "十堰市",
        province_en: "Hubei",
        city_en: "Shiyan",
        sort_order: 3,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "三峡大坝旅游区",
        name_en: "Three Gorges Dam Tourist Area",
        province: "湖北",
        city: "宜昌市",
        province_en: "Hubei",
        city_en: "Yichang",
        sort_order: 4,
        created_dt: now,
        record_status: "A",
      },
      // ── 湖南 Hunan ────────────────────────────────────────────────────────────
      {
        name_zh: "张家界武陵源景区",
        name_en: "Zhangjiajie Wulingyuan Scenic Area",
        province: "湖南",
        city: "张家界市",
        province_en: "Hunan",
        city_en: "Zhangjiajie",
        sort_order: 1,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "韶山旅游区",
        name_en: "Shaoshan Tourist Area",
        province: "湖南",
        city: "湘潭市",
        province_en: "Hunan",
        city_en: "Xiangtan",
        sort_order: 2,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "岳阳楼—洞庭湖景区",
        name_en: "Yueyang Tower–Dongting Lake Scenic Area",
        province: "湖南",
        city: "岳阳市",
        province_en: "Hunan",
        city_en: "Yueyang",
        sort_order: 3,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "崀山景区",
        name_en: "Langshan Scenic Area",
        province: "湖南",
        city: "邵阳市",
        province_en: "Hunan",
        city_en: "Shaoyang",
        sort_order: 4,
        created_dt: now,
        record_status: "A",
      },
      // ── 广东 Guangdong ────────────────────────────────────────────────────────
      {
        name_zh: "广州长隆旅游度假区",
        name_en: "Guangzhou Chimelong Tourist Resort",
        province: "广东",
        city: "广州市",
        province_en: "Guangdong",
        city_en: "Guangzhou",
        sort_order: 1,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "深圳华侨城旅游度假区",
        name_en: "Shenzhen OCT Tourist Resort",
        province: "广东",
        city: "深圳市",
        province_en: "Guangdong",
        city_en: "Shenzhen",
        sort_order: 2,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "丹霞山景区",
        name_en: "Danxia Mountain Scenic Area",
        province: "广东",
        city: "韶关市",
        province_en: "Guangdong",
        city_en: "Shaoguan",
        sort_order: 3,
        created_dt: now,
        record_status: "A",
      },
      // ── 广西 Guangxi ──────────────────────────────────────────────────────────
      {
        name_zh: "桂林漓江景区",
        name_en: "Guilin Lijiang River Scenic Area",
        province: "广西",
        city: "桂林市",
        province_en: "Guangxi",
        city_en: "Guilin",
        sort_order: 1,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "桂林独秀峰·王城景区",
        name_en: "Duxiufeng–Wangcheng Scenic Area",
        province: "广西",
        city: "桂林市",
        province_en: "Guangxi",
        city_en: "Guilin",
        sort_order: 2,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "德天跨国大瀑布景区",
        name_en: "Detian Transnational Waterfall",
        province: "广西",
        city: "崇左市",
        province_en: "Guangxi",
        city_en: "Chongzuo",
        sort_order: 3,
        created_dt: now,
        record_status: "A",
      },
      // ── 海南 Hainan ───────────────────────────────────────────────────────────
      {
        name_zh: "三亚南山文化旅游区",
        name_en: "Sanya Nanshan Cultural Tourism Zone",
        province: "海南",
        city: "三亚市",
        province_en: "Hainan",
        city_en: "Sanya",
        sort_order: 1,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "南湾猴岛生态旅游区",
        name_en: "Nanwan Monkey Island Eco-Tourism Area",
        province: "海南",
        city: "陵水县",
        province_en: "Hainan",
        city_en: "Lingshui",
        sort_order: 2,
        created_dt: now,
        record_status: "A",
      },
      // ── 重庆 Chongqing ────────────────────────────────────────────────────────
      {
        name_zh: "武隆喀斯特旅游区",
        name_en: "Wulong Karst Tourist Area",
        province: "重庆",
        city: "重庆市",
        province_en: "Chongqing",
        city_en: "Chongqing",
        sort_order: 1,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "大足石刻景区",
        name_en: "Dazu Rock Carvings",
        province: "重庆",
        city: "重庆市",
        province_en: "Chongqing",
        city_en: "Chongqing",
        sort_order: 2,
        created_dt: now,
        record_status: "A",
      },
      // ── 四川 Sichuan ──────────────────────────────────────────────────────────
      {
        name_zh: "九寨沟景区",
        name_en: "Jiuzhaigou Valley Scenic Area",
        province: "四川",
        city: "阿坝州",
        province_en: "Sichuan",
        city_en: "Aba Prefecture",
        sort_order: 1,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "峨眉山景区",
        name_en: "Mount Emei Scenic Area",
        province: "四川",
        city: "乐山市",
        province_en: "Sichuan",
        city_en: "Leshan",
        sort_order: 2,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "乐山大佛景区",
        name_en: "Leshan Giant Buddha Scenic Area",
        province: "四川",
        city: "乐山市",
        province_en: "Sichuan",
        city_en: "Leshan",
        sort_order: 3,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "都江堰景区",
        name_en: "Dujiangyan Irrigation System",
        province: "四川",
        city: "成都市",
        province_en: "Sichuan",
        city_en: "Chengdu",
        sort_order: 4,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "黄龙景区",
        name_en: "Huanglong Scenic Area",
        province: "四川",
        city: "阿坝州",
        province_en: "Sichuan",
        city_en: "Aba Prefecture",
        sort_order: 5,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "稻城亚丁景区",
        name_en: "Daocheng Yading Scenic Area",
        province: "四川",
        city: "甘孜州",
        province_en: "Sichuan",
        city_en: "Garze Prefecture",
        sort_order: 6,
        created_dt: now,
        record_status: "A",
      },
      // ── 贵州 Guizhou ──────────────────────────────────────────────────────────
      {
        name_zh: "黄果树瀑布景区",
        name_en: "Huangguoshu Waterfall Scenic Area",
        province: "贵州",
        city: "安顺市",
        province_en: "Guizhou",
        city_en: "Anshun",
        sort_order: 1,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "赤水丹霞旅游区",
        name_en: "Chishui Danxia Tourist Area",
        province: "贵州",
        city: "遵义市",
        province_en: "Guizhou",
        city_en: "Zunyi",
        sort_order: 2,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "荔波樟江景区",
        name_en: "Libo Zhangjia Scenic Area",
        province: "贵州",
        city: "黔南州",
        province_en: "Guizhou",
        city_en: "Qiannan Prefecture",
        sort_order: 3,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "梵净山景区",
        name_en: "Fanjing Mountain Scenic Area",
        province: "贵州",
        city: "铜仁市",
        province_en: "Guizhou",
        city_en: "Tongren",
        sort_order: 4,
        created_dt: now,
        record_status: "A",
      },
      // ── 云南 Yunnan ───────────────────────────────────────────────────────────
      {
        name_zh: "丽江古城景区",
        name_en: "Lijiang Ancient Town",
        province: "云南",
        city: "丽江市",
        province_en: "Yunnan",
        city_en: "Lijiang",
        sort_order: 1,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "石林风景区",
        name_en: "Stone Forest Scenic Area",
        province: "云南",
        city: "昆明市",
        province_en: "Yunnan",
        city_en: "Kunming",
        sort_order: 2,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "西双版纳景区",
        name_en: "Xishuangbanna Scenic Area",
        province: "云南",
        city: "西双版纳州",
        province_en: "Yunnan",
        city_en: "Xishuangbanna",
        sort_order: 3,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "香格里拉普达措国家公园",
        name_en: "Pudacuo National Park",
        province: "云南",
        city: "迪庆州",
        province_en: "Yunnan",
        city_en: "Diqing Prefecture",
        sort_order: 4,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "大理景区",
        name_en: "Dali Scenic Area",
        province: "云南",
        city: "大理州",
        province_en: "Yunnan",
        city_en: "Dali Prefecture",
        sort_order: 5,
        created_dt: now,
        record_status: "A",
      },
      // ── 西藏 Tibet ────────────────────────────────────────────────────────────
      {
        name_zh: "布达拉宫景区",
        name_en: "Potala Palace Scenic Area",
        province: "西藏",
        city: "拉萨市",
        province_en: "Tibet",
        city_en: "Lhasa",
        sort_order: 1,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "雅鲁藏布大峡谷旅游区",
        name_en: "Yarlung Tsangpo Grand Canyon",
        province: "西藏",
        city: "林芝市",
        province_en: "Tibet",
        city_en: "Nyingchi",
        sort_order: 2,
        created_dt: now,
        record_status: "A",
      },
      // ── 陕西 Shaanxi ──────────────────────────────────────────────────────────
      {
        name_zh: "秦始皇帝陵博物院",
        name_en: "Mausoleum of the First Qin Emperor (Terracotta Army)",
        province: "陕西",
        city: "西安市",
        province_en: "Shaanxi",
        city_en: "Xi'an",
        sort_order: 1,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "华山景区",
        name_en: "Huashan Mountain Scenic Area",
        province: "陕西",
        city: "渭南市",
        province_en: "Shaanxi",
        city_en: "Weinan",
        sort_order: 2,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "黄帝陵景区",
        name_en: "Huangdi Mausoleum (Yellow Emperor's Tomb)",
        province: "陕西",
        city: "延安市",
        province_en: "Shaanxi",
        city_en: "Yan'an",
        sort_order: 3,
        created_dt: now,
        record_status: "A",
      },
      // ── 甘肃 Gansu ────────────────────────────────────────────────────────────
      {
        name_zh: "敦煌莫高窟",
        name_en: "Dunhuang Mogao Caves",
        province: "甘肃",
        city: "酒泉市",
        province_en: "Gansu",
        city_en: "Jiuquan",
        sort_order: 1,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "嘉峪关文物景区",
        name_en: "Jiayuguan Fort",
        province: "甘肃",
        city: "嘉峪关市",
        province_en: "Gansu",
        city_en: "Jiayuguan",
        sort_order: 2,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "鸣沙山·月牙泉景区",
        name_en: "Mingsha Mountain and Crescent Moon Spring",
        province: "甘肃",
        city: "酒泉市",
        province_en: "Gansu",
        city_en: "Jiuquan",
        sort_order: 3,
        created_dt: now,
        record_status: "A",
      },
      // ── 青海 Qinghai ──────────────────────────────────────────────────────────
      {
        name_zh: "青海湖景区",
        name_en: "Qinghai Lake Scenic Area",
        province: "青海",
        city: "海南州",
        province_en: "Qinghai",
        city_en: "Hainan Prefecture",
        sort_order: 1,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "塔尔寺景区",
        name_en: "Kumbum Monastery (Ta'er Temple)",
        province: "青海",
        city: "西宁市",
        province_en: "Qinghai",
        city_en: "Xining",
        sort_order: 2,
        created_dt: now,
        record_status: "A",
      },
      // ── 宁夏 Ningxia ──────────────────────────────────────────────────────────
      {
        name_zh: "沙坡头旅游景区",
        name_en: "Shapotou Tourist Area",
        province: "宁夏",
        city: "中卫市",
        province_en: "Ningxia",
        city_en: "Zhongwei",
        sort_order: 1,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "西夏王陵景区",
        name_en: "Western Xia Imperial Mausoleums",
        province: "宁夏",
        city: "银川市",
        province_en: "Ningxia",
        city_en: "Yinchuan",
        sort_order: 2,
        created_dt: now,
        record_status: "A",
      },
      // ── 新疆 Xinjiang ─────────────────────────────────────────────────────────
      {
        name_zh: "天山天池风景名胜区",
        name_en: "Tianchi of Tianshan",
        province: "新疆",
        city: "昌吉州",
        province_en: "Xinjiang",
        city_en: "Changji Prefecture",
        sort_order: 1,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "喀纳斯景区",
        name_en: "Kanas Scenic Area",
        province: "新疆",
        city: "阿勒泰地区",
        province_en: "Xinjiang",
        city_en: "Altay Prefecture",
        sort_order: 2,
        created_dt: now,
        record_status: "A",
      },
      {
        name_zh: "楼兰景区",
        name_en: "Loulan Ancient City Scenic Area",
        province: "新疆",
        city: "巴音郭楞州",
        province_en: "Xinjiang",
        city_en: "Bayingolin Prefecture",
        sort_order: 3,
        created_dt: now,
        record_status: "A",
      },
    ]);
  }
}
